// Eye Tracking Beam Control
//
// DB9 interlock (relays):
//   Relay A (D4) = Enable — COM on DB9 pin 6, NC to pin 3 (GND), NO to pin 4
//                  (+12V Ref). Starts OFF (fail-safe) and stays off until the
//                  host sends E1, mirroring KCMH-Tricker's Enable checkbox
//                  instead of asserting the moment the board has power.
//   Relay B (D6) = Beam — COM on DB9 pin 1, NC to pin 3 (GND), NO to pin 4.
//   DB9 pin 4 is a passive rail: never switched, never tied to GND.
//
// ALPIDE trigger (J1 coax, 5 V):
//   D7 is OC4B, the Timer4 channel-B hardware PWM output, so the readout clock
//   is generated by the timer rather than by loop() — the frequency stays exact
//   regardless of what the serial handling is doing. Off until the host sends
//   T1. Replaces the trigger the KCMH FPGA supplies over LEMO when that box is
//   the one plugged into the TSS DB9.
//
//   NOTE: D6 (Relay B) is OC4A — the SAME timer. Only channel B is ever
//   connected to a pin (COM4A/COM4C stay 0), so D6 remains a plain GPIO that
//   digitalWrite() controls normally. Do not use analogWrite() on D6/D7/D8, and
//   do not digitalWrite(D7) while the trigger is running (Arduino's
//   digitalWrite clears COM4B1 and would silently kill the trigger output).
//
// Commands: B1\n = Beam ON,    B0\n = Beam OFF
//           E1\n = Enable ON,  E0\n = Enable OFF
//           H\n  = heartbeat (refreshes the relay watchdog, changes nothing)
//
// Replies: the board prints "EV B1 <n> <t>" / "EV B0 <n> <t>" whenever the beam
//          state actually changes, where <n> is the trigger pulse count since
//          T1 and <t> is 1 only if the trigger was running — <n> is a stale
//          leftover otherwise, since T0 does not clear the counter.
//          That count is the shared clock with the ALPIDE data — see
//          trig_pulses below. Periodic B1/B0 refreshes are not echoed.
//           T1\n = Trigger ON, T0\n = Trigger OFF
//           TF<hz>\n   set trigger frequency, 1..95000 Hz   (e.g. TF9500)
//           TD<pct>\n  set trigger duty cycle, 1..99 %      (e.g. TD50)
//           T?\n       print current trigger settings (bench debugging only —
//                      the app never sends this and never reads replies)
//           TSH\n / TSL\n  drive D7 statically high/low with no timer involved
//                      (bench debugging only — isolates wiring faults from
//                      timer-configuration faults)
//           TR?\n      dump the live Timer4 registers (bench debugging only)

#define RELAY_A  4
#define RELAY_B  6
#define TRIG_PIN 7

// Relay watchdog. Closing the serial port does NOT reset this board, so
// without this a crashed or hung host leaves both relays frozen in whatever
// state they were last commanded into — including Enable asserted with the
// DB9 live. Any recognised command refreshes the timer; if none arrives for
// WATCHDOG_MS the relays drop to the safe state and stay there until the host
// asserts them again. The host re-sends its intent periodically (see
// _send_heartbeat in app.py and the periodic B-state refresh in capture.py),
// so the hardware always converges on what the software actually wants.
//
// Deliberately guards the relays only, not the trigger: the trigger is a
// detector readout clock, not part of the beam interlock, and leaving it
// running costs nothing while a 2 s timeout would make bench measurements
// (which hold one state for minutes) unusable.
#define WATCHDOG_MS 2000UL

String input = "";

unsigned long trig_hz   = 9500;   // KCMH-Tricker's default readout frequency
uint8_t       trig_duty = 50;
bool          trig_on   = false;

bool          enable_on = false;
bool          beam_on   = false;

// Trigger pulse counter — the shared clock between this board and the ALPIDE
// data. Timer4 overflows once per PWM period in mode 14, so the count is the
// number of readout pulses emitted since T1, which (as long as no events are
// dropped) is the same index as the ALPIDE event number. Reporting the count at
// each beam transition is what lets "eye left the target" be located in the
// detector data without having to align two clocks.
volatile unsigned long trig_pulses = 0;

ISR(TIMER4_OVF_vect) { trig_pulses++; }

// Report a beam transition with the pulse count AND whether the trigger was
// actually running. T0 stops the trigger without clearing the counter, so a
// transition logged before T1 carries a leftover count from the previous run —
// a number that looks usable but means nothing. The flag is what tells the
// analysis which rows can be matched against the ALPIDE data.
unsigned long pulseCount();          // defined below

void reportEvent(const char *what) {
  Serial.print("EV ");
  Serial.print(what);
  Serial.print(' ');
  Serial.print(pulseCount());
  Serial.print(' ');
  Serial.println(trig_on ? 1 : 0);
}

unsigned long pulseCount() {
  unsigned long v;
  uint8_t sreg = SREG;
  cli();
  v = trig_pulses;
  SREG = sreg;
  return v;
}
unsigned long last_cmd_ms = 0;
bool          wd_tripped  = false;

// Program Timer4 for the current frequency/duty without touching channel A.
// Fast PWM mode 14: TOP = ICR4, so OCR4A stays free and D6 is unaffected.
void trigApply() {
  static const unsigned long presc[] = {1, 8, 64, 256, 1024};
  static const uint8_t       cs[]    = {1, 2,  3,   4,    5};

  uint8_t i = 0;
  unsigned long top = 65535UL;
  for (; i < 5; i++) {
    unsigned long ticks = F_CPU / (presc[i] * trig_hz);
    if (ticks < 2) ticks = 2;
    top = ticks - 1;
    if (top <= 65535UL) break;
  }
  if (i >= 5) { i = 4; top = 65535UL; }

  // non-inverting fast PWM holds the pin high for (OCR4B + 1) of (TOP + 1) ticks
  unsigned long high_ticks = ((top + 1UL) * trig_duty) / 100UL;
  if (high_ticks < 1)   high_ticks = 1;
  if (high_ticks > top) high_ticks = top;

  uint8_t live = TCCR4A & (1 << COM4B1);   // keep the output enabled if it was

  // OCR4B is double buffered in PWM modes but NOT in CTC/Normal, and the two
  // paths are different registers: a write made while the timer is still in
  // CTC lands in the compare register only, then the never-initialised buffer
  // overwrites it at the first BOTTOM. So select Fast PWM (WGM = 1110) with
  // the clock still stopped, and only then write OCR4B.
  TCCR4B = 0;                                    // halt (CS = 0)
  TCCR4A = (1 << WGM41) | live;                  // WGM41:40 = 10
  TCCR4B = (1 << WGM43) | (1 << WGM42);          // WGM43:42 = 11, still halted
  ICR4   = (uint16_t)top;
  OCR4B  = (uint16_t)(high_ticks - 1UL);
  TCNT4  = 0;
  TCCR4B = (1 << WGM43) | (1 << WGM42) | cs[i];  // start the clock
}

void trigStart() {
  trigApply();
  uint8_t sreg = SREG;
  cli();
  trig_pulses = 0;           // count from the start of this run
  SREG = sreg;
  TIFR4  = (1 << TOV4);      // clear a pending overflow before enabling
  TIMSK4 |= (1 << TOIE4);
  TCCR4A |= (1 << COM4B1);   // connect OC4B to D7
}

void trigStop() {
  TIMSK4 &= ~(1 << TOIE4);
  TCCR4A &= ~(1 << COM4B1);  // release D7 back to the port register
  digitalWrite(TRIG_PIN, LOW);
}

void setup() {
  Serial.begin(9600);
  pinMode(RELAY_A,  OUTPUT);
  pinMode(RELAY_B,  OUTPUT);
  pinMode(TRIG_PIN, OUTPUT);
  digitalWrite(RELAY_A,  LOW);   // Enable OFF until host sends E1
  digitalWrite(RELAY_B,  LOW);
  digitalWrite(TRIG_PIN, LOW);   // trigger OFF until host sends T1
  enable_on = false;
  beam_on   = false;
  last_cmd_ms = millis();
  input.reserve(16);
  delay(100);
  Serial.println("READY");
}

void loop() {
  if (!wd_tripped && (enable_on || beam_on) &&
      (millis() - last_cmd_ms) > WATCHDOG_MS) {
    digitalWrite(RELAY_B, LOW);        // beam first, then enable
    digitalWrite(RELAY_A, LOW);
    if (beam_on) { reportEvent("B0"); }
    beam_on   = false;
    enable_on = false;
    wd_tripped = true;
    Serial.println("WATCHDOG: host silent, relays dropped to safe state");
  }

  while (Serial.available()) {
    char c = Serial.read();
    if (c == '\n') {
      input.trim();
      if (input.length()) {
        last_cmd_ms = millis();
        wd_tripped  = false;
      }
      if (input == "B1") {
        digitalWrite(RELAY_B, HIGH);
        if (!beam_on) { reportEvent("B1"); }
        beam_on = true;
      } else if (input == "B0") {
        digitalWrite(RELAY_B, LOW);
        if (beam_on) { reportEvent("B0"); }
        beam_on = false;
      } else if (input == "E1") {
        digitalWrite(RELAY_A, HIGH);
        enable_on = true;
      } else if (input == "E0") {
        digitalWrite(RELAY_A, LOW);
        enable_on = false;
      } else if (input == "H") {
        // heartbeat: nothing to do, refreshing last_cmd_ms above is the point
      } else if (input == "T1") {
        trig_on = true;
        trigStart();
      } else if (input == "T0") {
        trig_on = false;
        trigStop();
      } else if (input.startsWith("TF")) {
        unsigned long v = (unsigned long)input.substring(2).toInt();
        if (v >= 1UL && v <= 95000UL) {
          trig_hz = v;
          if (trig_on) trigApply();
        }
      } else if (input.startsWith("TD")) {
        long v = input.substring(2).toInt();
        if (v >= 1 && v <= 99) {
          trig_duty = (uint8_t)v;
          if (trig_on) trigApply();
        }
      } else if (input == "TSH") {
        trig_on = false;
        trigStop();                      // release OC4B first
        digitalWrite(TRIG_PIN, HIGH);    // then drive the port bit directly
        Serial.println("D7 static HIGH");
      } else if (input == "TSL") {
        trig_on = false;
        trigStop();
        Serial.println("D7 static LOW");
      } else if (input == "TR?") {
        // dump the real Timer4 registers so a misconfiguration is visible
        // instead of inferred. Bench debugging only.
        uint16_t t1 = TCNT4;
        delay(50);
        uint16_t t2 = TCNT4;
        Serial.print("TCCR4A=0x"); Serial.print(TCCR4A, HEX);
        Serial.print(" TCCR4B=0x"); Serial.print(TCCR4B, HEX);
        Serial.print(" ICR4="); Serial.print(ICR4);
        Serial.print(" OCR4B="); Serial.print(OCR4B);
        Serial.print(" TCNT4:"); Serial.print(t1);
        Serial.print("->"); Serial.print(t2);
        Serial.print(" DDRH=0x"); Serial.print(DDRH, HEX);
        Serial.print(" PORTH=0x"); Serial.println(PORTH, HEX);
      } else if (input == "T?") {
        Serial.print("trig ");
        Serial.print(trig_on ? "ON " : "OFF ");
        Serial.print(trig_hz);
        Serial.print("Hz ");
        Serial.print(trig_duty);
        Serial.print("%  enable=");
        Serial.print(enable_on ? "1" : "0");
        Serial.print(" beam=");
        Serial.print(beam_on ? "1" : "0");
        Serial.print(" wd_tripped=");
        Serial.println(wd_tripped ? "1" : "0");
      }
      input = "";
    } else {
      input += c;
    }
  }
}
